In [1]:
import numpy as np

In [3]:
l1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Создание массива из списка
l2 = np.zeros((3,3)) # Создание массива нулей 3 на 3
l3 = np.ones((3,3)) # Единиц 3 на 3
l4 = np.arange(9) # Одномерный от 0 до 8

l1, l2, l3, l4

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [8]:
l2.shape, l2.dtype

((3, 3), dtype('float64'))

In [15]:
l4[3], l1[2, 1:3] # Сначала 3 элемент одномерного массива, потом 2 (3 если с 1) столбец элементы с 1 по 3 (со 2 по 4 не включительно)

(np.int64(3), array([8, 9]))

In [17]:
l1+l3, l1*l3 # Сложение и умножение матриц

(array([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]]),
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]))

In [20]:
np.mean(l1)

np.float64(5.0)